[Bug] [INTERNAL] [NBF]
Cause: None
Solution: None
Fixed Version: 20250222
Branch: main

diff --git a/frontend/.husky/prepare-commit-msg b/frontend/.husky/prepare-commit-msg
--- a/frontend/.husky/prepare-commit-msg
+++ b/frontend/.husky/prepare-commit-msg
@@ -1,15 +1,21 @@
 #!/bin/sh
-echo "Running prepare-commit-msg hook..."
-echo "Commit message file: $1"
-echo "Commit source: $2"
+# 获取提交信息文件路径
+COMMIT_MSG_FILE=$1
+
+COMMIT_SOURCE=$2
+
+# 如果用户使用 -m 参数，给出警告并退出
+if [ "$COMMIT_SOURCE" = "message" ]; then
+  echo "❌ Error: Direct commit messages are not allowed."
+  echo "Please use the default editor to provide a commit message with the template."
+  exit 1
+fi
 
 # 获取当前分支名
 BRANCH=$(git rev-parse --abbrev-ref HEAD)
-echo "Branch: $BRANCH"
 
 # 获取版本号
 VERSION=$(date '+%Y%m%d')
-echo "Version: $VERSION"
 
 # 定义模板内容
 TEMPLATE="[Bug] 
@@ -21,10 +27,4 @@ Solution: None
 Fixed Version: $VERSION
 Branch: $BRANCH"
 
-# 检查提交信息文件是否为空
-if [ -z "$(cat "$1")" ] && [ "$2" != "message" ]; then
-  echo "Inserting template..."
-  echo "$TEMPLATE" > "$1"
-else
-  echo "Skipping template insertion."
-fi
+echo "$TEMPLATE" > "$COMMIT_MSG_FILE"
